spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: nick1215
#mybatis:
#  mapper-locations: classpath:mapper/**.xml
#  configuration:
#    map-underscore-to-camel-case: true

logging:
  level:
    com:
      lishuangqi:
        test:
          mybatis:
            demo1:
              mapper: debug
